### ISSUE TITLE
Login credentials do not work, outdated code?

### ISSUE THREAD

**Issue by jagottsicher** [ianklatzco/twitter-to-bsky#20]
I hardcoded the credentials into main.py but get an error:

```
  File "C:\XXX\Python\Python311\Lib\site-packages\atprototools\__init__.py", line 19, in login
    raise ValueError("No access token, is your password wrong?")
ValueError: No access token, is your password wrong?
```
OS: windows 10
Put complete freshly downloaded archive in a network drive (mapped)
added the extracted repo there 
followed instruction from readme.md
login to bsky works in browser on same machine
latest python as well as pi and the dependencies (atprotocl?) installed.

Tried already:
updated atprototools to 0.0.17 Err: no method login.

What can I try to transfer my archive to bsky?

**Comment by jagottsicher** [comment]
Update
same problem on a linux based NAS
and a Linux desktop (debian based distro)
````
File "/XXX/python3.11/site-packages/atprototools/__init__.py", line 19, in login
    raise ValueError("No access token, is your password wrong?")
ValueError: No access token, is your password wrong?
```

**Comment by jagottsicher** [comment]
my bad: used the preceding part of the login as username only.

**Comment by jardicc** [comment]
I had few issues:
1) I used wrong version of at protocol
2) I used user handle instead of my email
3) I did not set env variables correctly... it is different on Windows :-D
