### ISSUE TITLE
issue on line 12 in main.py

### ISSUE THREAD

**Issue by metroville** [ianklatzco/twitter-to-bsky#23]
I've done all the steps (multiple times) and I have my assets folder in the same one as main.py, but my migration never begins because I get the following error:

line 12, in <module>
    f = open(TWEETS_JS_PATH)
FileNotFoundError: [Errno 2] No such file or directory: './data/tweets.js'

Anyone have a fix for this?

**Comment by metroville** [comment]
Here's a screenshot of exactly what I see in my terminal (with my username pseudo-covered, because I don't know) whenever I complete the final step and try to initiate the migration. Confusing.

<img width="644" alt="Screenshot 2024-11-10 at 8 35 43 PM" src="https://github.com/user-attachments/assets/f7b781ca-60c7-4fe6-b139-b2b7da500cae">

**Comment by metroville** [comment]
Solved it. The existing insructions have you move the assets folder from your downloaded Twitter data to the twitter-to-bsky-master folder, but **you also need to move the _data_ folder**. That was the issue for me, anyway, as those two folders were separate within the Twitter data folder. I'm basically a computer genius now.

**Comment by ianklatzco** [comment]
Nice!
